package com.liuruining.model.dao;

import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table book3.
 */
public class Book3 implements java.io.Serializable {

    private Long ID;
    private String spelling;
    private String meanning;
    private String phonetic_alphabet;
    private Long list;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Book3() {
    }

    public Book3(Long ID) {
        this.ID = ID;
    }

    public Book3(Long ID, String spelling, String meanning, String phonetic_alphabet, Long list) {
        this.ID = ID;
        this.spelling = spelling;
        this.meanning = meanning;
        this.phonetic_alphabet = phonetic_alphabet;
        this.list = list;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getSpelling() {
        return spelling;
    }

    public void setSpelling(String spelling) {
        this.spelling = spelling;
    }

    public String getMeanning() {
        return meanning;
    }

    public void setMeanning(String meanning) {
        this.meanning = meanning;
    }

    public String getPhonetic_alphabet() {
        return phonetic_alphabet;
    }

    public void setPhonetic_alphabet(String phonetic_alphabet) {
        this.phonetic_alphabet = phonetic_alphabet;
    }

    public Long getList() {
        return list;
    }

    public void setList(Long list) {
        this.list = list;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
