package com.liuruining.model.dao;

import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table word_location.
 */
public class WordLocation implements java.io.Serializable {

    private Long ID;
    private Integer book;
    private Integer index;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WordLocation() {
    }

    public WordLocation(Long ID) {
        this.ID = ID;
    }

    public WordLocation(Long ID, Integer book, Integer index) {
        this.ID = ID;
        this.book = book;
        this.index = index;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public Integer getBook() {
        return book;
    }

    public void setBook(Integer book) {
        this.book = book;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
